### ISSUE TITLE
Use libcore instead to support `no_std` environments

### ISSUE THREAD

**Issue by kevinaboos** [daboross/rust-throw#3]
This crate looks awesome, but us embedded rustaceans can't use any crates that depend on libstd. Looking at the source, it seems like there is no need for a dependency on std, as you can use `core::fmt` instead of `std::fmt`, but correct me if I'm wrong. I think it would just be a one-line change. 

Let me know if you'd like a pull request.

**Comment by daboross** [comment]
Sounds like a good change to me - thanks for reporting this!

I can implement this later this week, or if you want to make a PR that would also be good. An optional `std` feature which is enabled by default sounds like the best way to implement this, if that would work for your use case.

**Comment by kevinaboos** [comment]
Yeah, agreed, it's probably best to go with something like the `default-features = false` option that I see in some other crates. 
I can do a PR but am quite busy this week, so you'll likely beat me to it.

**Comment by daboross** [comment]
Alright! I've pushed a partial update which adds support for `no_std`.

The one caveat is that throw uses `Vec`, and thus depends on `alloc`. Unfortunately I'm not too familiar with the area: does embedded rust generally allow allocations?

We could definitely make a variation of `Error` storing error points in an `ArrayVec` rather than a `Vec`, but that would just be dead code if it wasn't needed.

**Comment by kevinaboos** [comment]
Some embedded environments do, some don't, but a dependency on `alloc` is fine if there's no way to get around it. In my case, I do support `alloc` types, so this works for me! Thanks very much for your hard work!

**Comment by daboross** [comment]
It's no problem - glad this library might be useful for something!

`StackError` without allocation could also reasonably exist - but it would mean inflating the size of `Result<T, StackError>` to the size of the max number of error points.

I'll release an update with support for `no_std` using `alloc` shortly.

**Comment by daboross** [comment]
Forgot to close this!

`nostd` is indeed supported now.
