### ISSUE TITLE
`throw::Error` doesn't implement `std::error::Error`

### ISSUE THREAD

**Issue by asib** [daboross/rust-throw#7]
Is there a design reason for this? I'm trying to use this crate with [Iron](https://docs.rs/iron), but I can't use a `throw::Error` as part of an `iron::error::Error` unless it implements `std::error::Error` (at least, I think).

If this is an acceptable change, I have a PR ready to go.

**Comment by daboross** [comment]
I can't think of any particular reason it isn't implemented. Adding it seems good! :+1:
